### ISSUE TITLE
JSX Atom Type

### ISSUE THREAD

**Issue by webberwang** [codelab-ai/builder#1317]
Refactor renderForEachPropKey and renderIfPropKey.

Instead of hard-coded use case on the element itself, we should model jsx and make the features more general.

The 2 above use cases are just general case of jsx code

```jsx
return (
  {apps.map(app => (
    <Title>{app.name}</Title>
  ))}
)
```

Suppose the above, we should have an atom type of jsx that allows us to type code.

Here `Title` should be prop mapped into this atom. So we would have some UI to map any name to existing atoms/components

**Comment by antonmihaylov** [comment]
Could you clarify a bit - should we allow the user to write the jsx code, like how they can write css right now? Or is this about abstracting different jsx operations

**Comment by webberwang** [comment]
> 

Well easier way would be to allow inline JSX, abstraction would prove too limiting & not application to the widest number of use cases

**Comment by antonmihaylov** [comment]
I think renderForEachPropKey and renderIfPropKey along with prop mapping can handle the majority of use cases. Maybe we should keep them to allow the most common cases to be done without custom code.

For custom JSX the biggest issue will most likely be running babel on-demand to convert JSX to React.createElement

**Comment by antonmihaylov** [comment]
An idea for abstracting this is something we already have - the render pipes. 
If we can add dynamic render pipes to each element we can handle a lot of cases.

Example:
```ts
const e: IElement  = {
...elementData,  
renderPipes: [
  {kind: ElementPipeKind.RenderIf, propName: 'item.name'},
  {kind: ElementPipeKind.RenderFor, propName: 'dataArray'},
  {kind: ElementPipeKind.RenderIfElse, propName: 'data', elseRender: 0x2 }, //component id
  ...etc
]}
```

Then we could generate dynamic render pipelines based on this.

This is of course not as flexible as custom code where you can handle all cases, but it's an alternative.

**Comment by webberwang** [comment]
> 

With regards to the most general approach, couldn't we have users write React without JSX using React.createElement?

**Comment by antonmihaylov** [comment]
Yeah, this should work. We would take the custom code in a render pipe, eval it to a function, and execute the function with the current props.

It could be at the atom level, where we would supply the result of [this](https://github.com/codelab-ai/web/blob/master/libs/frontend/modules/builder/src/renderer/pipes/renderAtomPipe.ts#L16)  as input
The code the user writes can look like this:
```js
function render(props, RactComponent) {
 return props.something ? React.createElement(ReactComponent, props) : null
}
```

Or we could move it a bit up and make it its own render pipe. It would look like this
```js
function render(element, context, props, next) => {
   if(!props.something) {
      return null
   }
     
  
   if(props.somethingElse} {
      // We would need to put the atomFactory inside the context to allow this
      return context. reactRender(context.atomFactory(element.atom), {newProps: "something"}) // same as React.createElement
   }

  return next(element, context, props)
}
```
