### ISSUE TITLE
Suggest new approach for adding text

### ISSUE THREAD

**Issue by webberwang** [codelab-ai/builder#1669]
@antonmihaylov let me know what you think of the new idea

---

## Issue

Adding `Text` as an atom creates no container since it uses fragments, so we can't add custom CSS to this. 

![web_–_Text_tsx_and_Home___Builder___Codelab_and_codelab-ai_web__Web_application_builder](https://user-images.githubusercontent.com/26264925/180882918-a90cd5fc-ca9d-43c2-888b-fefcfde5bd98.jpg)

Above, adding CSS to `Text A` doesn't do anything. Instead we had to add it to the parent element `Container A`

## Proposal

Instead of creating `Text` as a new children atom, we add it to existing atom as a prop of `children` perhaps. This `children` will take primitive values here.

**Comment by antonmihaylov** [comment]
Yes, having the text as a separate element always seemed a bit unintuitive.

We could add it to the children prop, that sounds like a good idea. 
In the right sidebar, we would just need a text field that directly edits props.children as a string.

Bonus point - we can also implement double click to edit an element's text using contenteditable.

**Comment by antonmihaylov** [comment]
Fixed in #1703
