### ISSUE TITLE
Remove the need to use a separate element for adding text

### ISSUE THREAD

**Issue by antonmihaylov** [codelab-ai/builder#1672]
## Description

Adding text is a very common operation, using another element and attaching an atom of type text is unintuitive.
#1669  outlines other problems with it. 

## Proposed solution
- Add a text field here that will directly edit element.props.children as a text.  
<img width="297" alt="image" src="https://user-images.githubusercontent.com/57956282/180961525-cf70e826-d0ad-4c01-a692-24bd5ad63dda.png">

- Dynamic state variable replacement should work naturally as it's just another prop, but test it

- We should disable it for some AtomTypes, for example adding it to input, other void HTML tags, or some AntD/MUI atoms that don't take in any children doesn't make sense.

- Check out how it will interact if we have both element.props.children and regular children. My guess is that the regular children will override the text, which sounds reasonable.
  e.g.: 
```
Parent {props: {children: "Some text"}}
    \_ Child
```
Will this render 
`<Parent><Child/></Parent>` (this seems more appropriate to me)
Or 
`<Parent>Some text</Parent>`

## Future ideas
- Double-clicking an element in the builder triggers it to become contenteditable and directly edits props.children that way

**Comment by mohasarc** [comment]
I also think it makes more sense to replace the text with the children if any exist, but I have a few questions:

- The user has to remove the children first then add text? maybe we should disable the text input field when there are any children.
- Will we internally use Text Atom? If so, I think we'd need to automatically create the Text atom for any new app.

**Comment by antonmihaylov** [comment]
It won't replace the actual child elements. It will be stored in elements.props.children. 

It's a good idea to disable the text input when there are children already since it would be confusing to have both.

I don't see any need for a text atom if you can set the text of any element using this method. For example, if you want a simple "text" field you can add a span and enter some text in it.

Good question. I suppose the direct approach is to add an Em element, then a Strong element, etc. But that's cumbersome.
What if instead of props.children it modifies `dangerouslySetInnerHTML. __html `? That way the user can enter any HTML. And it solves the children vs props.children problem, since If I'm not mistaken, __html will overwrite everything. The UI can be using Codemirror with html syntax

**Comment by mohasarc** [comment]
Oh I just realized that setting `elements.props.children` would produce the behaviour that we're looking for - rendering text if no children and rendering children if they exist; I wasn't aware of that before.

Using `props.dangerouslySetInnerHTML.__html` seems interesting since it gives more flexibility to the user. In this case are we gonna pass the `props.children` as `dangerouslySetInnerHTML.__html` to the `React.createElement()`? or shall we store it differently?

**Comment by antonmihaylov** [comment]
If we're gonna use html, you can store it directly in "element.props.dangerouslySetInnerHTML.__html", right? It will get passed through like any other prop, no need for props.children

**Comment by mohasarc** [comment]
Yeah, I think so.

**Comment by mohasarc** [comment]
What do you think about adding this field into `Props` tab instead of `Node` tab. Also calling it `innerHtml`?

**Comment by antonmihaylov** [comment]
Can you clarify - name what innerHtml - the field label?

**Comment by mohasarc** [comment]
Yes, so we have a default field in the `Props` tab, that's called `innerHtml` which is applicable to all elements.

**Comment by antonmihaylov** [comment]
Oh wait I misunderstood, you mean it would have sort of a default field in the atoms api for all atoms? I was thinking a normal field, like css is for example

**Comment by mohasarc** [comment]
Well it could also be a normal UI-only field that appears in the `props` tab for any selected element.

**Comment by antonmihaylov** [comment]
Yeah, let's keep the Interface Form for dynamic api props only

**Comment by mohasarc** [comment]
Ok, then I think this is what I'm gonna do:

- Create a simple form called `InnerHtmlForm`
- Add it to `UpdateElementPropsForm` alongside (above) `PropsForm`
- When `InnerHtmlForm` value updated patch the element using `elementService.patchElement()` to update `props.dangerouslySetInnerHTML.__html`

**Comment by antonmihaylov** [comment]
Sounds good
