### ISSUE TITLE
Misc refactors

### ISSUE THREAD

**Issue by webberwang** [codelab-ai/builder#1677]
- [x] Consistent naming

![Mouse_Highlight_Overlay](https://user-images.githubusercontent.com/26264925/181042313-f6b26eb2-0c16-4946-824e-590ba62fccaf.jpg)

These 2 are the same thing but have different naming, which can be confusing. I see the motivation was to differentiate `onChange` & `onCheckedChange`.

I think `onCheckedChange` can be renamed to `onCheck` instead.

- [ ] Renaming function (this may be opinionated let me know your thoughts)

![Mouse_Highlight_Overlay](https://user-images.githubusercontent.com/26264925/181043787-8c7bdb84-985e-4373-87a2-fc082373f21a.jpg)

I think the `prop` is redundant here `matchCssPropUnit` -> `matchCssUnit`. Although the string is from a prop, the source of the input doesn't really matter, as long as it contains a `cssUnit`

Also instead of `match`, the word `extract` seems more fitting. A `match` could have multiple matches, but `extract` returns just one substring

![Mouse_Highlight_Overlay](https://user-images.githubusercontent.com/26264925/181046687-c93ef19a-6325-4675-be29-c349e50ac7e0.jpg)

(above is an example of using the terminology)

So `matchCssPropUnit` -> `extractCssUnit`

**Comment by mohasarc** [comment]
Yeah that's a nice name. The motivation of having `prop` in the name was to indicate that it doesn't work on more complex strings (designed to work with css property's value). but I guess adding a comment would be better.
