### ISSUE TITLE
A shortcut button to edit/add props to an atom API

### ISSUE THREAD

**Issue by mohasarc** [codelab-ai/builder#1704]
## Description
when opening the props tab of an element whose atom has no props, it is a bit confusing and unclear where/how to add a prop. It would be very helpful to have a button to directly add a prop to the atom API from the props tab. An alternative appproach would be just to add some text clarifying why is the tab empty and how to add a prop.

![Screenshot from 2022-08-07 17-48-52](https://user-images.githubusercontent.com/51242349/183297353-73491fe4-8f3c-4692-b6c2-c445e79f6b84.png)

## Suggested Implementation
A button when clicked opens `typeService.fieldCreateModal`.

**Comment by antonmihaylov** [comment]
That's a good idea. I think a simple text with a link to the page where you edit the API would be nice

**Comment by webberwang** [comment]
A normal user wouldn't be able to modify an atom (although in https://github.com/codelab-ai/builder/issues/1696 we are discussing the possibility of that). The props would be filled in by an admin before MVP release.

Nonetheless, a link would still be a good idea for admins to use.

**Comment by antonmihaylov** [comment]
Ah right, we could show it only for admins
