### ISSUE TITLE
Deleting root element of a page makes /pages inaccessible

### ISSUE THREAD

**Issue by mohasarc** [codelab-ai/builder#1755]
## Current Behavior
It is possible to delete the root element of a page using keybord's `delete`. Then neither the page itself nor `/pages` is accessible.

## Expected Behavior

One or both of the following:
- Should not allow deleting root element.
- Should not throw an error if there is not root element.

## Steps to Reproduce

https://user-images.githubusercontent.com/51242349/187031938-fa4ecf25-e2f1-4e25-a4eb-1a59ae9902a1.mp4

**Comment by webberwang** [comment]
We shouldn't be able to delete the body element, could provide a pure frontend solution in the meantime

**Comment by melhamin** [comment]
@webberwang I noticed that we can't delete non-root elements using hotkeys. If `del` is pressed when a non-root element is selected, the delete modal opens for the root element. Somehow, `useBuilderHotkeys` always gets the root element as the `selectedNode`.

I will add the guard to not allow deleting the root element. Should I fix the bug I mentioned above in this issue or create a new one?

**Comment by webberwang** [comment]
@melhamin you can add to same PR as different commit if the PR isn't too large. It's arbitrary to say when a PR gets too large, but I think in this case is okay
