### ISSUE TITLE
Residual left after prop is deleted

### ISSUE THREAD

**Issue by mohasarc** [codelab-ai/builder#1758]
## Current Behavior

although a prop is deleted from the atom's api, the elements of that prop keep having that prop and its last value before deletion.

## Expected Behavior

No residual should be left.

## Steps to Reproduce

https://user-images.githubusercontent.com/51242349/187069078-58a993be-74c7-4582-a51e-60daf0ffd3dc.mp4

**Comment by webberwang** [comment]
We could create a @cypher directive for deleting interfaces to also delete all associated data for that interface

**Comment by webberwang** [comment]
I believe after deleting a page, the root element is left over. Similar so we can combine the PR
