### ISSUE TITLE
Schema Modeling Refactor

### ISSUE THREAD

**Issue by webberwang** [codelab-ai/builder#1772]
Do we need to connect `App` & `Element` model? Couldn't we traverse from `Element` to `App` through `Page` instead.

This goes for many other models as well, the bottom line is that I don't think we need to add relationships for the sole reason of caching information, traversal is enough to accomplish that.

---

`Element.instanceOfComponent` & `Element.component` can be confusing, since they are used in different context. The first is used in a page element tree, while the second is used in component tree only.

- Change `Element.instanceOfComponent` to `Element.componentType` (I suppose this could be used in component tree as well if we allow nested component types.
- Change `Element.atom` to `Element.atomType`

We use more consistent vocabulary, as an Element could by either an `Atom` or `Component` type.

- Change `Element.component` to `Element.componentParent`
- Does User need to Own element? We can check the owner indirectly

**Comment by antonmihaylov** [comment]
> Do we need to connect App & Element model? 

I can't tell without the use case, why are App and Element connected in the first place, I can't seem to find where it's used. 

> Element.instanceOfComponent & Element.component can be confusing

I don't see a reason for this breaking change, they are commented, and the new naming doesn't make it as clear as you wouldn't need to read the comments anyway. It is confusing but if you're going to change it, might as well make it clearer. For example - move this to a separate object, like `ElementInstanceType` which could be one of `ComponentElementInstance { componentId: string }` or `AtomElementInstance {atomId: string}`. I'm not sure how well this will play with neo4j-graphql though.

> Does User need to Own element?
I think that's important. Yes, we can check the owner, but authorization is something you do on every single request. It would be much faster to just check element.userId than to go through the db. Of course that's a different story if it's cached in Redis or something similar

**Comment by webberwang** [comment]
A new model would make more sense, we'll keep it for now. 

Right authorization is the main part here
