### ISSUE TITLE
Misc Refactor (Domain, Tag, Element)

### ISSUE THREAD

**Issue by webberwang** [codelab-ai/builder#1800]
- [x] Why is `shouldUpdateCache` used in ElementService?

---

- [x] What is the purpose of the `@computed` from?

![image](https://user-images.githubusercontent.com/26264925/189386584-f954ebae-2a60-4c8b-8cba-ebe52705d8d8.png)
---
- [x] Refactor reoslvers

- Try to avoid any, use some generated type if we can
- Unhandled promise
- Same for all domain resolvers

![builder_–_domain-config_resolver_ts](https://user-images.githubusercontent.com/26264925/189386877-670380c2-6395-4883-89d8-08348c4b7f31.jpg)

---

- [x] What is the significance of `IGraphQLTagNode`?

![Cursor_and_builder_–_tagtree_service_interface_ts](https://user-images.githubusercontent.com/26264925/189391120-d60df04d-38f6-46d0-8818-c12b0f6c20e9.jpg)

**Comment by phmngocnghia** [comment]
`Why is shouldUpdateCache used in ElementService?`

This is an add-on parameter that skips the updating cache when we want to make multiple changes to an element, and bulk updates the cache. It's not used anymore as we have a bulk update function that takes multiple mutations, and we can provide our own update cache function. I'll remove it
